# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique_for_date='pubdate')),
                ('pubdate', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('in_stock', models.BooleanField(db_index=True, default=True, verbose_name='In stock')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Category')),
            ],
            options={
                'verbose_name': 'good',
                'ordering': ['-price', 'name'],
                'verbose_name_plural': 'goods',
            },
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together=set([('category', 'price', 'name')]),
        ),
    ]
